[package]
name = "klipo"
version = "0.1.0"
description = "A clipboard manager"
authors = ["gustavosvalentim"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "klipo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "tray-icon" ] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clipboard-rs = { version = "=0.3.5", features = ["wayland"] }
md-5 = "0.11.0"
image = { version = "0.25", default-features = false, features = ["png"] }
base64 = "0.22"
enigo = "0.6.1"
tokio = { version = "1", features = ["time"] }
rusqlite = { version = "0.32", features = ["bundled"] }
log = { version = "0.4", features = ["kv_serde"] }

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[target."cfg(target_os = \"macos\")".dependencies]
objc2-app-kit = { version = "0.3.2", features = ["NSColor", "NSWindow", "NSWorkspace", "NSRunningApplication", "objc2-core-foundation"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
